# Generated by Django 3.1.2 on 2020-10-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Climbing', 'Climbing'), ('Soccer', 'Soccer'), ('Football', 'Football'), ('Ultimate Frisbee', 'Ultimate Frisbee'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Basketball', 'Basketball'), ('Vollyball', 'Vollyball'), ('Cycling', 'Cycling'), ('Golf', 'Golf'), ('Cornhole', 'Cornhole'), ('Baseball', 'Baseball'), ('Softball', 'Softball'), ('Zumba', 'Zumba'), ('Lifing', 'Lifting'), ('Cricket', 'Cricket'), ('Tennis', 'Tennis'), ('Spikeball', 'Spikeball'), ('Other', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=2)),
                ('sport', models.ManyToManyField(to='WebApp.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.profile')),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.activities')),
            ],
        ),
    ]
