# Generated by Django 3.1.2 on 2020-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('C', 'Climbing'), ('S', 'Soccer'), ('F', 'Football'), ('U', 'Ultimate Frisbee'), ('Y', 'Yoga'), ('R', 'Running'), ('B', 'Basketball'), ('V', 'Vollyball'), ('CY', 'Cycling'), ('G', 'Golf'), ('CO', 'Cornhole'), ('BA', 'Baseball'), ('SB', 'Softball'), ('Z', 'Zumba'), ('L', 'Lifting'), ('', 'Golf'), ('CO', 'Cornhole'), ('BA', 'Baseball')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ManyToManyField(to='WebApp.Selection'),
        ),
    ]
