# Generated by Django 3.1.2 on 2020-10-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20201008_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='cornhole',
            field=models.CharField(default='Cornhole', max_length=15),
        ),
        migrations.AlterField(
            model_name='selection',
            name='sport',
            field=models.CharField(choices=[('C', 'Climbing'), ('S', 'Soccer'), ('F', 'Football'), ('U', 'Ultimate Frisbee'), ('Y', 'Yoga'), ('R', 'Running'), ('B', 'Basketball'), ('V', 'Vollyball'), ('CY', 'Cycling'), ('G', 'Golf'), ('CO', 'Cornhole'), ('BA', 'Baseball'), ('SB', 'Softball'), ('Z', 'Zumba'), ('L', 'Lifting'), ('G', 'Golf'), ('CO', 'Cornhole'), ('BA', 'Baseball')], max_length=15),
        ),
    ]
