# Generated by Django 3.1.2 on 2020-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20201008_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.CharField(choices=[('Soccer', 'soccer'), ('Vollyball', 'vollyball'), ('Climbing', 'climbing')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
