# Generated by Django 3.1.2 on 2020-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20201008_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sport',
        ),
        migrations.AddField(
            model_name='profile',
            name='sport1',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Vollyball', 'Vollyball'), ('Climbing', 'Climbing'), ('Football', 'Football'), ('Zumba', 'Zumba'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Golf', 'Golf'), ('Cornhole', 'Cornhole'), ('Ultimate', 'Ultimate'), ('Basketball', 'Basketball'), ('Softball', 'Softball'), ('Lifting', 'Lifting')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sport2',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Vollyball', 'Vollyball'), ('Climbing', 'Climbing'), ('Football', 'Football'), ('Zumba', 'Zumba'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Golf', 'Golf'), ('Cornhole', 'Cornhole'), ('Ultimate', 'Ultimate'), ('Basketball', 'Basketball'), ('Softball', 'Softball'), ('Lifting', 'Lifting')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sport3',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Vollyball', 'Vollyball'), ('Climbing', 'Climbing'), ('Football', 'Football'), ('Zumba', 'Zumba'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Golf', 'Golf'), ('Cornhole', 'Cornhole'), ('Ultimate', 'Ultimate'), ('Basketball', 'Basketball'), ('Softball', 'Softball'), ('Lifting', 'Lifting')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
